enyojs/enyo

source/data/Model.js
tools/mocha-tests/tests/Model.js

Cherry-picking changes from https://github.com/enyojs/enyo/pull/965 into `2.5.1-release`, creating a PR for tracking purposes.

ENYO-726: Adding fix for ENYO-653 (2.5.1.1)

---

tools/minifier/node_modules/less-plugin-resolution-independence/lib/resolution-independence.js

Reverting the changes from https://github.com/enyojs/enyo/pull/986, creating a PR for tracking purposes.
Revert "Merge pull request #986 from enyojs/ENYO-720-revert-kunmyon"
This reverts commit 77c62d64a68338abe0e74debc3d737163f54b2f2, reversing
changes made to 74264a4fccf4b3bcf508afbe58018b3b52f4c152.

ENYO-720: Update base font-size

---

source/ui/Animator.js

Cherry-picking the changes from https://github.com/enyojs/enyo/pull/989 into `master`, creating a PR for tracking purposes.

ENYO-719 (master)

---

source/ui/Input.js

Cherry-picking the changes from https://github.com/enyojs/enyo/pull/1001 into `2.5-upkeep`, creating a PR for tracking purposes.

ENYO-860 (2.5)

---

source/boot/version.js
source/dom/dom.js
source/ui/data/VerticalDelegate.js
tools/deploy.js
tools/less.js
tools/minifier/lessc.js
tools/minifier/minify.js
tools/minifier/node_modules/less-plugin-resolution-independence/README.md
tools/minifier/node_modules/less-plugin-resolution-independence/lib/index.js
tools/minifier/node_modules/less-plugin-resolution-independence/lib/resolution-independence.js
tools/minifier/node_modules/less-plugin-resolution-independence/lib/usage.js
tools/minifier/node_modules/less-plugin-resolution-independence/package.json
tools/minifier/node_modules/walker.js

It's time to bring the band back together and merge `2.5-gordon` into `master`.
We rebase `2.5-gordon` on `master` to prevent merging in any duplicate commits (some had been previously cherry-picked already).

ENYO-873: Merge 2.5-gordon into master

---

source/dom/dom.js

Cherry-picking the changes from https://github.com/enyojs/enyo/pull/943 into `release-2.5.3-pre.8.w`, creating a PR for tracking purposes.

ENYO-867 (2.5.3-pre.8.w)

---

source/dom/dom.js

Cherry-picking the changes from https://github.com/enyojs/enyo/pull/943 into `2.5-upkeep`, creating a PR for tracking purposes.

ENYO-867 (2.5-upkeep)

---

source/dom/dom.js

Cherry-picking the changes from https://github.com/enyojs/enyo/pull/963 into `release-2.5.3-pre.8.w`, creating a PR for tracking purposes.

ENYO-868 (2.5.3-pre.8.w)

---

source/dom/dom.js

Cherry-picking the changes from https://github.com/enyojs/enyo/pull/963 into `2.5-upkeep`, creating a PR for tracking purposes.

ENYO-868 (2.5)

---

source/ui/data/VerticalDelegate.js

Fixes ENYO-899: Prevent incorrect page positioning.

---

source/ui/data/DataList.js
source/ui/data/VerticalDelegate.js
source/ui/data/VerticalGridDelegate.js

Cherry-picking the changes from https://github.com/enyojs/enyo/pull/960 into `release-2.5.3-pre.10.w`, creating a PR for tracking purposes.

ENYO-527 (2.5.3-pre.10.w)

---

source/ui/data/DataList.js
source/ui/data/VerticalDelegate.js
source/ui/data/VerticalGridDelegate.js

Cherry-picking the changes from https://github.com/enyojs/enyo/pull/960 into `2.5-upkeep`, creating a PR for tracking purposes.

ENYO-527 (2.5)

---

tools/less-ri.js
tools/less.js

Cherry-picking the changes from https://github.com/enyojs/enyo/pull/1026 into `master`, creating a PR for tracking purposes.

ENYO-952 (master)

---

source/ui/resolution.js

Body classes are now applied, helper functions added and documentation updated.

ENYO-958: Added screen aspect ratio support and detection.

---

samples/SpriteAnimationSample.css
samples/SpriteAnimationSample.js
source/ui/SpriteAnimation.js

Sample updated to display new code.

ENYO-804: Added an alternate JavaScript timing mechanism for animation on low-powered hardware.

---

samples/SpriteAnimationSample.css
samples/SpriteAnimationSample.js
source/ui/SpriteAnimation.js

Cherry-picking the changes from https://github.com/enyojs/enyo/pull/1030 into `release-2.5.3-pre.13.-t`, creating a PR for tracking purposes.

ENYO-804 (2.5.3-pre.13.t)

---

samples/SpriteAnimationSample.css
samples/SpriteAnimationSample.js
source/ui/SpriteAnimation.js

Cherry-picking the changes from https://github.com/enyojs/enyo/pull/1030 into `2.5-upkeep`, creating a PR for tracking purposes.

ENYO-804( 2.5-upkeep)

---

source/data/Collection.js

Cherry-picking the changes from https://github.com/enyojs/enyo/pull/1038 into `2.5-upkeep`, creating a PR for tracking purposes.

ENYO-1025 (2.5-upkeep)

---

source/ui/LightPanels.js

Adding support for specifying timing function, changing defaults

---

source/ui/LightPanels.js

Adding support for enqueueing views to pre-cache. General clean-up.

---

source/ui/LightPanels.js

Adding panel-caching feature to enyo.LightPanels (wip)

---

source/ui/LightPanels.js

ENYO-944: Some minor performance tweaks.

---

source/dom/Control.js

At the moment the accessibility code using enyo.Control.extend is in
garnet library, but there is an issue that accessibilityLabelChanged
isn't called on W2 because of noDefer option. So move the code to
enyo.Control to fix the problem.
https://jira2.lgsvl.com/browse/ENYO-986

ENYO-986 : Move accessibility code from garnet to enyo control

---

source/data/Collection.js

This reverts commit 6207563847982a941179892dca15c568bd6ddf90.

Revert "ENYO-1025: Fix index issue in Collection.add() with purge: true"

---

source/dom/Control.js

Cherry-picking the changes from https://github.com/enyojs/enyo/pull/1046 into `release-2.5.3-pre.14.w`, creating a PR for tracking purposes.

ENYO-986 (2.5.3-pre.14.w)

---

source/dom/dispatcher.js

Cherry-picking the changes from https://github.com/enyojs/enyo/pull/1050 into `master`, creating a PR for tracking purposes.

ENYO-1098 (master)

---

source/kernel/Component.js
source/kernel/Loop.js
source/kernel/jobs.js
source/kernel/package.js
source/ui/LightPanels.js
tools/test/core/tests/AnimatorTest.js
tools/test/core/tests/ComponentTest.js
tools/test/core/tests/JobsTest.js

- Fix issue with transition not being reset.
- Add initial support for deferred panel loading [WIP].
- Cherry-picking the implementation of `enyo.Loop` and reworked `enyo.jobs`.

A cornucopia of changes

---

source/ui/LightPanels.js

ENYO-1082: Corrected bug with queue, updated queue pruning logic.

---

source/ui/LightPanels.js

ENYO-1082: Fixing logic error, backloading queue processing work.

---

source/ui/LightPanels.js

ENYO-1082: Restore current pre-caching mechanism.

---

source/ui/LightPanels.js

ENYO-944: Restore preCacheQueuedPanels.

---

source/ui/LightPanels.js

ENYO-1082: Utilize run loop for panels view caching.

---

source/ui/LightPanels.js

ENYO-1022: Add note for follow-on work.

---

source/ui/LightPanels.js

ENYO-944: Only animate if generated.

---

source/ui/LightPanels.js

ENYO-944: Immediately setup next panel when no animation is required.

---

source/ui/LightPanels.js

ENYO-944: Utilizing better semantics, general clean-up.

---

source/kernel/UiComponent.js
source/ui/LightPanels.js

ENYO-944: Fix bug with ordering of controls when using renderOnShow.

---

source/ui/LightPanels.js

ENYO-944: Prevent pre-caching of duplicate panels.

---

source/ui/LightPanels.js

Allow for panel caching in either direction.

---

source/ui/LightPanels.js

ENYO-944: Update pushPanels method.

---

source/ui/package.js
source/ui/wip-package.js

ENYO-944: Move LightPanels to WIP.

---

source/data/Collection.js
source/data/Model.js
source/data/States.js

ENYO-260 Fix enums

---

source/enyo.design

Fixed the design.js file !!!   Add enyo.scrim
ENYO-4133   :)
Enyo-DCO-1.1 Signed-off-by: Signed-off-by: johnmcconnell@yahoo.com

2.5.1 release

---

tools/test/core/tests/ComponentJobTest.js
tools/test/core/tests/ComponentTest.js
tools/test/core/tests/package.js

ENYO-944: Disable jobs-related testing.

---

samples/LightPanelsSample.html
source/ui/LightPanels.js

ENYO-944: Add option to force post-transition work. General clean-up.

---

source/ui/LightPanels.js

ENYO-944: Only determine if panel exists if we're caching.

---

source/ui/LightPanels.js

There are situations where we want a given panel to be placed in its post-transition position, even when that transition has not been directly triggered.
We perform some refactoring of the transition position code and expose this as a private method.

ENYO-944: Allow for placing a panel in its "final" location when needed.

---

source/ui/LightPanels.js

ENYO-944: Add hooks for panel activated/deactivated.

---

source/enyo.design

Enyo-DCO-1.1 Signed-off-by: Signed-off-by: johnmcconnell@yahoo.com

Add enyo Scrim that was skiped/missed by LG

---

source/kernel/BackgroundTaskManager.js
source/kernel/SystemMonitor.js

ENYO-944: Some clean-up and edge-case handling.

---

source/data/FluxDispatcher.js
source/data/FluxStore.js
source/data/package.js
source/data/wip-package.js

Cherry-picking the changes from the `enyo-flux-derekanderson` branch for integration into `ENYO-944`.

ENYO-944: Adding flux support.

---

source/touch/Scrollable.js
source/ui/data/NewDataList.js
source/ui/data/VirtualDataRepeater.js

ENYO-1341: Miscellaneous fixes for NewDataList

---

source/data/FluxStore.js

Add missing change from 243ff29 for FluxStore

---

source/touch/Scrollable.js

When we're already scrolling and we are asked to scroll a node
into view that is in the opposite direction of our current scroll
direction, we need to recheck node visibility against the scroll
destination and potentially reverse course.

ENYO-1445: Fix scrollToNode in reverse-direction case

---

lib/Component.js
lib/NewDataList.js
lib/NewThumb/package.json
lib/ScrollMath.js
lib/Scrollable.js
lib/VirtualDataRepeater.js

Migrated to modularized codebase for merging into 2.6.0-dev.
Also includes fixes for a couple of issues found during testing:
* componentOverrides were not working
* There was a typo in the package.json for enyo/NewThumb

Compilation of changes since 2.6.0-pre.4

---

lib/DataGridList/DataGridList.js

correct mapping of vertical grid delete

Fixes ENYO-1552

---

lib/Group/Group.js
lib/Group/GroupAccessibilitySupport.js
lib/Group/package.json

Add group role and set 'aria-activedescendant'
Enyo-DCO-1.1-Signed-off-by: Jaewon Jang jaewon98.jang@lgepartner.com

Fixes ENYO-1639

---

lib/Table/Table.js
lib/Table/TableAccessibilitySupport.js
lib/Table/package.json
lib/TableCell/TableCell.js
lib/TableCell/TableCellAccessibilitySupport.js
lib/TableCell/package.json
lib/TableRow/TableRow.js
lib/TableRow/TableRowAccessibilitySupport.js
lib/TableRow/package.json

Add accessibility support for tables
- add grid role in Table
- add row role in TableRow
- add gridcell role in TableCell

Fixes ENYO-1640

---

lib/Scroller/Scroller.css

This reverts commit 1bf350f29f0471969af5e6b8b76f96a85294a57d, reversing
changes made to 188a54e390c0db799b7c2aaa0a3a43bd261cf5c3.

ENYO-1566: Revert "Merge pull request #1145 from enyojs/ENYO-1542-kunmyonchoi-2.6"

---

lib/Scroller/Scroller.css
lib/TouchScrollStrategy.js
lib/TransitionScrollStrategy.js
lib/TranslateScrollStrategy.js

Changes from https://github.com/enyojs/enyo/pull/1181.

ENYO-1566: Scroller doesn't display last line when using p tag on content

---

tools/deploy.js
tools/minifier/lessc.js
tools/minifier/minify.js

Changes from https://github.com/enyojs/enyo/pull/1171.

ENYO-1667 (2.5.3-pre.20.wb)

---

tools/minifier/node_modules/less-plugin-resolution-independence/lib/resolution-independence.js

Changes from https://github.com/enyojs/enyo/pull/1199.

ENYO-1787: Convert nested measurement values. (2.5.3-pre.22.wb)

---

source/ui/Animator.js

ENYO-1791: Add complete method to Animator

---

lib/AccessibilitySupport/AccessibilitySupport.js
lib/Button/ButtonAccessibilitySupport.js
lib/Checkbox/CheckboxAccessibilitySupport.js
lib/Group/GroupAccessibilitySupport.js
lib/Input/InputAccessibilitySupport.js
lib/Popup/PopupAccessibilitySupport.js
lib/RichText/RichTextAccessibilitySupport.js
lib/Table/TableAccessibilitySupport.js
lib/TableCell/TableCellAccessibilitySupport.js
lib/TableRow/TableRowAccessibilitySupport.js
lib/TextArea/TextAreaAccessibilitySupport.js
test/tests/AccessibilitySupport.js

Fixes ENYO-1689

---

css/mixins.less
package.json

Add rtl-compatible margin and padding mixins

Fixes ENYO-2009

---

lib/DataRepeater.js
lib/VerticalDelegate.js

ENYO-2161: Fix selection support when using native JS data objects

---

lib/Image/Image.css

This reverts commit 65c07bdfb6a684c269b843232b465a682a573387, reversing
changes made to ee55e3c801849a2e35a50f68357a51d6f6172e1b.

Revert "Merge pull request #1256 from enyojs/ENYO-2313-graynorton"

---

src/Controller.js
test/tests/Controller.js

Failing unit-test due to bad test (not updated with singleton code). Add additional guard to Controller constructor.
Enyo-DCO-1.1-Signed-Off-By: Cole Davis (cole.davis@lge.com)

Fix for: ENYO-2460

---

src/Image/Image.css
src/Image/Image.js

Enyo 2313 roysutton - unrevert placeholder change

---

src/Control/Control.js

ensure that the next time the tag renders it will do so properly
Enyo-DCO-1.1-Signed-Off-By: Cole Davis (cole.davis@lge.com)

Fix for: ENYO-2310

---

package.json

Enyo-DCO-1.1-Signed-off-by: Art Dahm art.dahm@lge.com

ENYO-2441 Fix failing Enyo unit tests and re-enable testing on Travis

---

src/kind.js

add kind() method to Kind constructors

Fixes ENYO-2619

---

gulpfile.js
package.json

Fixes ENYO-2622 add back linting for npm test

---

src/Control/Control.js
src/dom.js

ENYO-2674: Exit early if addClass receives no classname

---

src/NewDataList.js
src/ScrollMath.js
src/Scrollable/Scrollable.js

ENYO-2644: Revert flawed initial fix, try another approach

---

src/VirtualDataRepeater.js

Our old logic for updating `childrenByIndex` worked in most cases,
but wasn't bullet-proof. In particular, it didn't do well in cases
where the indices of existing children changed in "irregular" ways.
The issue that exposed the problem was one in which a filter was
applied to the underlying collection, causing a potentially random
set of items to "disappear" and the indices of remaining items to
change, but similar problems could also have occurred when
non-contiguous items were added or removed, or when items were
reordered. The new logic should work in all such cases.
Also did some minor cleanup and added some inline comments
describing the logic in the infamous `doIt()` method.

ENYO-2669: VDR: Fix issue with child index

---

src/History.js

add history to the top of the queue when added during processing

Fixes ENYO-2766

---

src/History.js

A prior change updated clear() to only reset the internal history so
this change corrects clear() to both reset the internal history and
keep the browser history in sync.

Fixes ENYO-2699

---

css/mixins.less
src/Control/fullscreen.less

reset padding and margin for fullscreen ancestors

Fixes ENYO-2771

---

src/DataList/DataList.js
src/VerticalDelegate.js

ENYO-2808 Add warning about incorrect fixedChildSize

---

src/ViewManager/ViewManager.js

Also add dragging property to distinguish between dismiss events

Fixes PLAT-12048 add dismiss event when dragging VM

---

src/LightPanels/LightPanels.js

Fixes ENYO-2858 prevent scrolling when focusing on a panel while transitioning in

---

src/AccessibilitySupport/AccessibilitySupport.js

prevent update a11y attributes when unchanged

Fixes ENYO-2844

---

src/ViewLayout/ViewLayout.js
src/ViewManager/ViewManager.js

Fixes PLAT-13424 prevent setting dragging when not really dragging

---

src/BackgroundTaskManager.js
src/FluxDispatcher.js
src/FluxStore.js
src/LightPanels/LightPanel.js
src/LightPanels/LightPanels.js
src/NewAnimator.js
src/NewDataList.js
src/NewDrawer/NewDrawer.js
src/NewThumb/NewThumb.js
src/PriorityQueue.js
src/SystemMonitor.js
src/TaskManagerSupport.js
src/ViewPreloadSupport.js

ENYO-2917 Document wip modules/kinds

---

docs/external.jsdoc

ENYO-2904 Add glossary entries for private/protected

---

src/StylesheetSupport.js

ENYO-2964 Fix mixin declarations

---

src/ViewManager/ViewManager.js

If a drag is brief enough, we might only see a dragstart and dragfinish
thereby skipping the validation logic in handleDrag(). Refactoring that
logic out into a method so it can be called from both handlers.

Fixes PLAT-14490

---

src/DataGridList/DataGridList.js

ENYO-2646 Move contructor to create

---

src/platform.js

ENYO-2486 ENYO-3012 Add edge detection, fix docs

---

src/RepeaterChildSupport.js

ENYO-3020: Cleanup unnecessary comments

---

src/Checkbox/Checkbox.js

ENYO-3031: Fix broken comment block

---

src/TransitionScrollStrategy.js

There are some existing quirks and oddities with `enyo/TransitionScrollStrategy`, as it is still experimental.
To better identify that the implementation is not finalized and there can be existing issues, we mark this module as WIP.

ENYO-3053: Mark TransitionScrollStrategy as WIP.

---

src/Component.js
src/Repeater.js
src/pageVisibility.js

ENYO-1810 Cleanup in-line samples for modules

---

src/animation.js

Enyo-DCO-1.1-Signed-off-by: Jason Robitaille <jason.robitaille@lge.com>

ENYO-3080: requestAnimationFrame not in usage for iOS >=7

---

src/ViewLayout/ViewLayout.js

Changes from https://github.com/enyojs/enyo/pull/1375.

ENYO-3071 (2.6.1-pre.6)

---

src/gesture/drag.js

Changes from https://github.com/enyojs/enyo/pull/1365.

ENYO-3038 (2.6.1-pre.6)

---

src/SlideViewLayout/SlideViewLayout.js
src/SlideViewLayout/SlideViewLayout.less

Changes from https://github.com/enyojs/enyo/commit/94e218babb64ab9325df8a0a2fe6d1f4a4a7a009.

PLAT-14017

---

src/Binding.js
src/LightPanels/LightPanel.js
src/LightPanels/LightPanels.js
src/Relation.js
src/RelationalModel/RelationalCollection.js
src/RelationalModel/RelationalModel.js
src/RelationalModel/index.js
src/RelationalModel/manyToMany.js
src/RelationalModel/toMany.js
src/RelationalModel/toOne.js

ENYO-3078 Updated Docs to prevent duplicate modules

---

src/LightPanels/LightPanels.js
src/ViewPreloadSupport.js

Changes from https://github.com/enyojs/enyo/pull/1362.

PLAT-15150 (2.6.0-rc.2)

---

src/VerticalDelegate.js

Fixes ENYO-2867 clear the model for unrendered rows of a DataRepeater

---

src/Collection.js
src/LinkedList.js

There is some outdated documentation, related to string kind names.
Documentation has been updated!

ENYO-3112: Update documentation.

---

src/AccessibilitySupport/AccessibilitySupport.js

Changes from https://github.com/enyojs/enyo/pull/1334.

ENYO-2844 (2.6.3-rc.1)

---

src/LightPanels/LightPanels.js

Changes from https://github.com/enyojs/enyo/pull/1343.

ENYO-2913 (2.6.3-rc.1)

---

src/Collection.js
src/EventEmitter.js
src/ObserverSupport.js
src/RelationalModel/RelationalModel.js

Changes from https://github.com/enyojs/enyo/pull/1372.

ENYO-2990 (2.6.3 rc.1)

---

src/RepeaterChildSupport.js

Fixes ENYO-3126 add docs for RepeaterChildSupport#selectedClass

---

src/LightPanels/LightPanels.js

Changes from https://github.com/enyojs/enyo/pull/1376.

ENYO-2951 (2.6.4-rc.1)

---

src/LightPanels/LightPanels.js

Changes from https://github.com/enyojs/enyo/pull/1384.

ENYO-3011 (2.6.4 rc.1)

---

src/History.js

Changes from https://github.com/enyojs/enyo/pull/1366.

PLAT-15389 (2.6.4-rc.1)

---

src/SpriteAnimation/SpriteAnimation.js

ENYO-3175: Added support for Mozilla based browsers

---

src/Ajax.js
src/Checkbox/Checkbox.js
src/Control/fullscreen.js
src/Input/Input.js
src/Select.js
src/Table/Table.js
src/dispatcher.js
src/dom.js
src/gesture/drag.js
src/gesture/util.js
src/i18n.js
src/ready.js
src/touch.js
src/utils.js

Removing core support for IE8
Enyo-DCO-1.1-Signed-off-by: Jeremy Thomas <jeremy.thomas@lge.com>

ENYO-3019: IE8 Support Removal

---

src/dispatcher.js

Enyo-DCO-1.1-Signed-off-by: Jason Robitaille <jason.robitaille@lge.com>

ENYO-3192: Dispatcher not caching touch position as expected

---

src/touch.js

https://jira2.lgsvl.com/browse/PLAT-17001
Enyo-DCO-1.1-Signed-off-by: Mikyung Kim <mikyung27.kim@lge.com>

PLAT-17001: Not to change target of touchmove events

---

src/gesture/drag.js
src/gesture/gesture.js
src/gesture/util.js
src/touch.js

https://jira2.lgsvl.com/browse/PLAT-17002
Enyo-DCO-1.1-Signed-off-by: Mikyung Kim <mikyung27.kim@lge.com>

PLAT-17002: Added scrollMode to prevent generating unwanted events

---

src/Scroller/Scroller.js

Enyo-DCO-1.1-Signed-off-by: Roy Sutton roy.sutton@lge.com

ENYO-3247 Correct docs for strategyKind

---

src/Video.js

Fixes ENYO-3093 guard setting Video current time from Infinity

---

src/Video.js

Changes from https://github.com/enyojs/enyo/pull/1428.

ENYO-3093 (2.6.3-rc.2)

---

src/VerticalDelegate.js
src/VerticalGridDelegate.js

Changes from https://github.com/enyojs/enyo/pull/1402.

ENYO-3158 (2.6.4-rc.1)

---

src/LightPanels/LightPanels.js

Changes from https://github.com/enyojs/enyo/pull/1376.

ENYO-2951 (2.6.3-rc.2)

---

src/Scroller/Scroller.js

ENYO-3261: Update default scrollStrategy for iOS devices

---

src/NewDataList.js
src/NewDrawer/NewDrawer.js
src/NewThumb/NewThumb.js
src/Scrollable/Scrollable.js
src/VirtualDataRepeater.js

* VirtualDataRepeater
* Scrollable
* NewDataList
* NewThumb
* NewDrawer

Documentation for WIP features:

---

src/LightPanels/LightPanels.js

Changes from https://github.com/enyojs/enyo/pull/1384.

ENYO-3329 (2.6.3-rc.4)

---

src/dom.js
src/resolution.js

Changes from https://github.com/enyojs/enyo/pull/1456.

PLAT-23335 (2.6.3-rc.11.s)
