enyojs/enyo

tools/minifier/node_modules/less-plugin-resolution-independence/lib/resolution-independence.js

It appears that negatively-valued measurements with a non-standard unit, such as `apx`, will be handled by LESS as a combination of a string value and a unit object. This differs from how a positively-valued measurement with the same non-standard unit is handled (the entire measurement, including the unit, is treated as a single string).
We add an additional conditional to handle the case where the value and absolute unit are separated. Additionally, we change the name of this absolute unit property from `_ignoreUnit` to the more-appropriate and clearly-named `_absoluteUnit`. Lastly, we fix a latent documentation issue with the options that can be passed into our resolution-independence LESS plugin.

ENYO-735: Handle measurements with negative apx values.

---

tools/minifier/node_modules/less-plugin-resolution-independence/lib/resolution-independence.js

The resolution-independence plugin had been assuming integer measurement values.
We utilize `parseFloat` to account for fractional measurement values.

ENYO-750: Properly handle fractional measurements.

---

tools/minifier/node_modules/less-plugin-resolution-independence/lib/resolution-independence.js

Values such as `1px` in FHD resolution were being converted to rem-based units, and would resolve to a value < 1px in HD resolution, which was undesired and caused visual defects.
We prevent the conversion of measurements that are less than a specific threshold value (defaulted to `1`), based on a given minimum resolution (defaulted to `8` to correspond to the root font-size of this resolution). Additionally, we fix a latent issue where we are assuming integer values for measurements.

ENYO-738: Prevent unnecessary conversion of small values.

---

source/ui/data/DataRepeater.js
source/ui/data/RepeaterChildSupport.js
tools/mocha-tests/tests/DataGridList.js
tools/mocha-tests/tests/DataList.js
tools/mocha-tests/tests/DataRepeater.js

We had various selection states (`selection`, `multipleSelection`, `groupSelection`) which were becoming out of sync due to mutual exclusion and some coupling. This was somewhat evidenced in the DataGridListSample when toggling the various selection states.
We have introduced a new property called `selectionType`, which can be of the value `single` (the default), `multi`, or `group`. Because there was never any logic previously enforcing the fact that multiple selection automatically enables selection in general, we ignore this logic and do not make any assumptions about setting `selection` based on `selectionType`, to keep a cleaner separation between the properties. The `selectionType` property is effectively set via the deprecated selection properties (`multipleSelection` and …

ENYO-643: Synchronize selection states.

---

tools/minifier/node_modules/less-plugin-resolution-independence/lib/resolution-independence.js

We are not currently limiting the number of decimal places for our converted resolution-independent measurements, resulting in long floating point numbers.
A new property `precision` has been added to the resolution-independence plugin, that defaults to a value of `5`. Additionally, general clean-up and refactoring was done to improve semantics and specifically to separate out the logic for parsing a rule with a string value vs. a rule with separate value and unit objects. Lastly, some hardening was done to catch some other edge cases with unit parsing, and an unnecessary return statement was removed from `visitRule` as we are not specifying `isReplacing:true` in our plugin.

ENYO-772: Allow specification of measurement precision.

---

tools/deploy.js

Current deploy.js aborts if app directory does not have icon.png or index.html in case that it does not have a extra deploy.json file.
Enyo-DCO-1.1-Signed-off-by Junil Kim <logyourself@gmail.com>

ENYO-4124: deploy.js should work regardless of icon.png or index.html existence

---

source/ui/Animator.js

moon.Panel.transitionFinished is not called by moon.Panels
Added `enyo.Animator.complete()` to simplify enyo.Panels implementation

Fixes ENYO-719

---

source/boot/boot.js

This fix apparently got lost in 4e3bef5 (original fix: 6dbc4a9)
Enyo-DCO-1.1-Signed-off-by: Johann Jacobsohn j.jacobsohn@satzmedia.de

readd charset to generated script elements for internet explorer

---

source/data/Model.js

Issue.
`Model.restore()` did not work appropriately, because quick cloning was used, which maintained prototypical inheritance, causing `this.previous` to maintain current values of the model.
Fix.
Remove quick cloning on lines where this.previous was being set to a copy of attributes.
Enyo-DCO-1.1-Signed-off-by: Derek Anderson <derek.anderson@lge.com>

ENYO-521: removed quick clone from this.previous

---

source/ajax/Ajax.js

IE8 doesn't property support `onprogress` events so enyo.Ajax.updateProgress errors when attempting to reference properties on the event object (which isn't passed for IE8).
Suppress calls to progress handlers for IE8 by guarding for undefined event

Fixes ENYO-787

---

source/boot/version.js
source/dom/dom.js
source/ui/Animator.js
tools/deploy.js
tools/less.js
tools/minifier/lessc.js
tools/minifier/minify.js
tools/minifier/node_modules/less-plugin-resolution-independence/README.md
tools/minifier/node_modules/less-plugin-resolution-independence/lib/index.js
tools/minifier/node_modules/less-plugin-resolution-independence/lib/resolution-independence.js
tools/minifier/node_modules/less-plugin-resolution-independence/lib/usage.js
tools/minifier/node_modules/less-plugin-resolution-independence/package.json
tools/minifier/node_modules/walker.js

It's time to bring the band back together and merge `2.5-gordon` into `2.5-upkeep`.
We rebase `2.5-gordon` on `2.5-upkeep` to prevent merging in any duplicate commits (some had been previously cherry-picked already).

ENYO-872: Merge 2.5-gordon into 2.5-upkeep

---

source/ui/data/VerticalDelegate.js

When there are exactly two pages in a DataList, there are issues with navigating between pages. This can be seen very clearly when adding an item to the collection or triggering a refresh of the list. Due to optimizations we made to clean-up page assignment logic (via https://github.com/enyojs/enyo/commit/f91c7b), we introduced a situation where the second page can have an index of 0. There is existing logic in `pagesByPosition` to assign a default value to the pages under the assumption no index exists - this results in a value of 0 for the second page's index being set to a value of 1, causing both the first and the second page to have the same, computed position.
In `pagesByPosition`, we allow for a value of 0 for the index of the second page to be a valid index that is not set to 1. …

ENYO-899: Prevent incorrect page positioning.

---

source/ui/data/DataList.js
source/ui/data/VerticalDelegate.js
source/ui/data/VerticalGridDelegate.js

Need to provide API to determine which controls are visible for a DataList and DataGridList.
Add `getVisibleControlRange()` to enyo.DataList which returns the `start` and `end` index of the visible controls. For a control to be considered visible, a certain percentage (established by the `visibleThreshold` property) must be visible.

Fixes ENYO-527

---

source/data/Model.js

Issue.
When changing the value of an attribute, the previous value is not maintained except during construction and committing. Expectation is that the previous value should be retained anytime the attribute is updated.
Fix.
Ensure that we copy the previous attributes value, into the previous object's keys.
Enyo-DCO-1.1-Signed-off-by: Derek Anderson <derek.anderson@lge.com>

ENYO-521: updated keeping key value between changes

---

tools/less-ri.js
tools/less.js

When developing in the browser using resolution-independent versions of the framework, there is no way to disable this feature and test standard measurement versions (i.e. only pixels).
We add a new script `less-ri.js`, which is a resolution-independent version of `less.js`, that can be referenced by developers wanting to utilize resolution-independent features when developing locally. We are able to remove some of the resolution-independent-specific tweaks we made in `less.js` as those can now be encapsulated in `less-ri.js`.

ENYO-952: Add resolution-independent version of less.js

---

samples/ImageSample.js
source/ui/Image.js

The `position` property of `enyo.Image` was not working at all.
We retrieve the correct property in response to `position` being set, and also perform necessary logic at create time. Additionally, the sample has been updated to demonstrate the use of this property.

ENYO-881: Fix position property.

---

source/dom/dispatcher.js

On app change state between BG and FG, div which is under cursor is not getting onleave event.
While marquee is flow on hover, it is not stop because it is not getting onleave event when app  goes to BG.
- Add blur on windowEvents array to handle on dispatcher feature. (Core)
- Remember last hovered marqueeSupport control on global variable. (Marquee)
- Call onleave event handler of last hovered marqueeSupport control when app is getting onblur event. (Marquee)
DCO-1.1-Signed-Off-By: Kunmyon Choi kunmyon.choi@lge.com

ENYO-923: Stop marquee when window throw blur event

---

source/data/Collection.js

The logic in VerticalDelegate to avoid unnecessary refreshes on
modelsAdded was being tripped up by an issue with Collection.add
in the case where the 'purge' option was set to true.
Specifically, the insertion index reported by Collection.add was
not properly adjusted in the case where models had been purged.

ENYO-1025: Fix index issue in Collection.add() with purge: true

---

source/data/Collection.js

Cherry-picking the changes from https://github.com/enyojs/enyo/pull/1038 into `release-2.5.3-pre.13.t`, creating a PR for tracking purposes.

ENYO-1025 (2.5.3-pre.13.t)

---

source/dom/dispatcher.js

When (0, 0) is tapped on drawers, drawers do not open/close.
We have a code to filter out simulated click event in Spotlight onClick handler.
And, it is checking clientX/clientY == 0 to know is that a simulated event.
That is eventually filter out normal click event also.
Add a flag to indicate the event is generated from click event.
This can be used in Spotlight to exactly distinguish simulated event.
DCO-1.1-Signed-Off-By: Kunmyon Choi kunmyon.choi@lge.com

ENYO-1098: Adding simulated flag on generated tap event

---

tools/deploy.js

When deploying an Enyo application, if there are LESS files in Enyo core that are part of the manifest, an error will be thrown. This is due to the fact that by default, LESS processing is disabled just for Enyo core, which tries to access the equivalent file with the `css` instead of `less` extension; because this file does not exist in most cases, an error is thrown.
We explicitly pass in the `less` flag when invoking the minifier for Enyo core, to match what is occurring when minifying the rest of the application. We could also update the minifier to default to LESS parsing being enabled, but this seems to be tightly-interleaved with the deploy script, so I wanted to make this change first and then potentially revisit cleaning up both the deploy script and the minifier. …

ENYO-1161: Specify "less" option when minifying Enyo lib.

---

samples/SelectSample.js
source/ui/Select.js

enyo.Select.selected isn't a bindable property (as it should be) and setting the value of selected at create time is not respected.
Some refactoring was needed to ensure the property changes were being applied in the right order and in the correct way (e.g. by using `set()` instead of modifying the member directly).
This PR supercedes #1024. Thanks @appsbychris for much of the work to resolve this!

Fixes ENYO-988 and ENYO-1032

---

source/data/Collection.js
source/data/Model.js
source/data/States.js

Note: links for @types to enums in the enyo namespace don't work

ENYO-460 Enums weren't linked correctly

---

source/dom/Control.js

When a control is shown, the `onShowingChanged` event is waterfalled. The original intent of `renderOnShow` was to allow a parent control to selectively render a child control by directly showing the control; this seems to be in conflict with rendering the control in response to a waterfalled `onShowingChanged` event, as is the current behavior.
We remove the code that renders a `renderOnShow:true` control in response to an `onShowingChanged` event.

ENYO-944: Only render when directly shown.

---

source/ui/LightPanels.js

The `transitioning` class was being applied with the same transition delay as the actual transition values, causing the transition to sometimes be skipped or drop a number of frames.
We only apply the transition delay to applying the transition values, and immediately apply the class and transition duration/function.

ENYO-944: Apply transition styles earlier.

---

source/ui/LightPanels.js
source/ui/ViewPreloadSupport.js
source/ui/wip-package.js

- Factored out view-caching support into a mixin.
- Added support for specifying a direct transition option when pushing a panel or panels.
- General clean-up and code reorganization.

ENYO-944: Refactoring and adding direct transition option support

---

samples/LightPanelsSample.html
source/ui/LightPanels.js

Two issues addressed here. The first issue is that we moved some of the BTM-related kinds to a wip-package and the `LightPanelsSample` needed to reference this manifest. The second issue is that for each call to `pushPanels`, there are multiple calls to an expensive `panelExists` method. This is partially cruft and partially stop-gap for how we are dealing with routing in the app. This stop-gap should not be part of `enyo.LightPanels` anyways, and has been addressed in the app code.
The sample has been updated to reference the manifest, and `enyo.LightPanels` has been cleaned-up with the removal of `panelExists` and the associated calls to this method.

ENYO-944: Update sample, further optimize pushPanels.

---

source/ui/data/VerticalDelegate.js

Issue
------
A page generated once, and it is not fully filled page.
And some models are added without re-generate that page.
We we call scrollToIndex over that page, generatePage() is called infinitely.
Cause
--------
Model adding does not update partially filled page's bounds
FIx
-----
The last page of list can be partially filled if models are not equally distributed to every page.
However if new models are added and then list has more pages than before,
previous last page must be fully filled.
Currently that last page does not update its metric until it is generated again.
So, list.bufferSize could miss calculate it.
We can prevent this edge case with this commit.
Enyo-DCO-1.1-Signed-off-by: David Um david.um@lge.com

ENYO-1200 Update partially filled page when models are added.

---

source/ui/LightPanels.js

If no priority is provided when enqueueing views to be pre-cached, the default priority is not utilized.
The default priority is now utilized if none is provided.

Use default priority for panel pre-caching task, as needed.

---

source/kernel/Router.js

When utilizing the `useHistory` property of `enyo.Router`, the `back` action could not properly set the location as `location` is a computed property.
We instead call the computed property method `location`, passing in the desired location as a parameter.

Properly update location when initiating a "back" action.

---

source/ui/LightPanels.js

Based on some clean-up in https://github.com/enyojs/moonstone/pull/2066, we no longer need an explicit call to `shouldSkipPostTransition`.
The call to `shouldSkipPostTransition` has been removed.

Remove unnecessary call to shouldSkipPostTransition.

---

source/ui/LightPanels.js

We had originally been forcing an index change when pushing a panel(s).
This was some crufty logic because the initial index value is `0`. This has been changed to default to `-1`, which corresponds to not inaccurately having an index value of `0` when there are no panels.

Prevent forcing an index change.

---

source/ui/LightPanels.js

We made a previous fix to prevent the unnecessary forcing of an index change when pushing a panel or panels, but this prevented switching of panels in the purge state, as the panel index remained at `0` in this case.
When purging, we reset the panel index to the default value of `-1`.

Reset panel index when purging.

---

source/kernel/TaskManagerSupport.js
source/ui/LightPanels.js

Each task manager would have to set their own default priority.
We include a standard default priority as part of the `TaskManagerSupport` mixin.

Update default priority to be part of mixin.

---

source/ui/data/NewDataList.js

We recently added some code to stabilize (bring within range) the
scroll threshold values in cases where the list size has just
changed (a fix for ENYO-1349).
This fix wasn't working properly in the case where the list was
entirely or nearly emptied, so accounting for that case now.

ENYO-1454: Fix threshold stabilization in NewDataList

---

source/dom/accessibility.js

The "accessibilityLabel" property covers ARIA attribute "aria-label".
If "accessibilityLabel" is set, add "aria-label" and make the control
tabbable by setting a tabindex=0.
Screen reader reads "aria-label" when the control is focused.
https://jira2.lgsvl.com/browse/ENYO-1122
Enyo-DCO-1.1-Signed-off-by: Jaewon Jang jaewon98.jang@lgepartner.com

ENYO-1122: Add "accessibilityLabel" to enyo control

---

source/dom/accessibility.js

AccessibilityHint is used for additional information of control. If
accessibilityHint is set and content exists, screen reader reads
accessibilityHint with content when control is focused.
For example there is a button and if button clicked, image or video will
be played. In this case blind needs to know what will happen after
clicking button.
AccessibilityHint can explain the result of action and describe
something need to more information.
https://jira2.lgsvl.com/browse/ENYO-1125
Enyo-DCO-1.1-Signed-off-by: Jaewon Jang jaewon98.jang@lgepartner.com

ENYO-1125: Accessibility: Add "accessibilityHint" to enyo control

---

source/dom/accessibility.js

The accessibilityAlert property is to cover alert role of aria
attribute.
Basically screen reader reads content or accessibilityLabel out when the
control is focused, but there are some cases that it should be read
something regardless focus. For example, popup, notifications, page
description and so on. If accessibilityAlert is set true, screen reader
will automatically reads content or accessibilityLabel when the control
is rendered or visible.
Refer
https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_alert_role.
https://jira2.lgsvl.com/browse/ENYO-1124
Enyo-DCO-1.1-Signed-off-by: Jaewon Jang jaewon98.jang@lgepartner.com

ENYO-1124: Accessibility: Add "accessibilityAlert" to enyo control

---

source/dom/accessibility.js

The accessibilityLive is to cover "aria-live" of aria attribute.
In case of dynamic content which updates without a page reload, it needs
to read current value out. If accessibilityLive is set true, screen
reader will read current value of content without any focus whenever it
changed.
https://jira2.lgsvl.com/browse/ENYO-1234

ENYO-1234: Accessibility: Add "accessibilityLive" to enyo control

---

source/dom/accessibility.js

The readAlert API is for calling tts api of system service. Most of
cases accessibility supports focus based readout, but ux scenario
sometimes wants application reads a message dynamically. We provides the
readAlert API to cover it.
https://jira2.lgsvl.com/browse/ENYO-1126

ENYO-1126: Accessibility: Add "readAlert()" to enyo

---

lib/LightPanels/LightPanels.js
lib/TaskManagerSupport.js

"Cherry-picking" changes to `enyo.LightPanels` from `2.6.0-pre.4-dev` to `2.6.0-dev`.

[2.6.0-pre.4-dev -> 2.6.0-dev] LightPanels updates and refinement.

---

lib/Router.js

"Cherry-picking" the changes from https://github.com/enyojs/enyo/pull/1110 into `2.6.0-dev`.

[2.6.0-pre.4-dev -> 2.6.0-dev] Properly update location when initiating a "back" action.

---

lib/FluxStore.js

"Cherry-picking" the changes from https://github.com/enyojs/enyo/pull/1119 into `2.6.0-dev`.

[2.6.0-pre.4-dev -> 2.6.0-dev] Add missing change from 243ff29 for FluxStore

---

lib/LightPanels/LightPanels.js

We had previously been assuming that the `kind` property of a view would be the unique identifier when pre-caching views. This had been abstracted into a mixin, and the `getViewId` method is implemented by the control utilizing that mixin.
After this change, we forgot to update `pushPanels` (only `pushPanel` was updated) to utilize the `getViewId` method. This has now been corrected. Additionally, the `id` property has been changed to `panelId` to prevent collisions with the actual `id` property.

ENYO-1556: Utilize the getViewId method for determining view id, rather than assuming the kind property.

---

source/dom/accessibility.js

The accessibilityDisabled is to be disable voice readout for control.
In some requirements, it should not read anything when control is
focused, so we provide accessibilityDisabled property to cover that.
If accessibilityDisabled is true, aria attributes are removed for the
control.
https://jira2.lgsvl.com/browse/ENYO-1123

ENYO-1123: Accessibility: Add "accessibilityDisabled" to enyo control

---

lib/RelationalModel/RelationalCollection.js
lib/RelationalModel/RelationalModel.js
lib/RelationalModel/index.js
lib/RelationalModel/manyToMany.js
lib/RelationalModel/package.json
lib/RelationalModel/toMany.js
lib/RelationalModel/toOne.js
test/tests/RelationalModel.js

There is a circular module dependency between RelationalModel, toMany, and RelationalCollection.
* Remove the dependency on the relation types from RelationalModel and refactor RelationalModel.concat to support the change.
* Add RelationalModel.defineRelationType to register named types on RelationalModel to support string-based relation type definition (as currently supported).
* Move the RelationalModel-related code into a submodule

Fixes ENYO-1519

---

lib/LightPanels/LightPanels.js
lib/ViewPreloadSupport.js

The pre-caching of a panel can trigger the `update` method of the same view that initiated the pre-caching of this panel, resulting in an infinite set of pre-caching tasks to be queued and run. This had previously been guarded by examining the unique identifier of the view, in the `ViewPreloadSupport` mixin, but this needs to be updated to support the latest modular changes.
We guard against pre-caching a panel that has already been cached, which should have been guarded against to begin with. We also update the call to `addTask` to utilize the string identifier of the panel, instead of the `kind` object, due to the modular changes.

ENYO-1567: Guard against already-cached panels from being re-cached.

---

lib/VirtualDataRepeater.js

For expediency during initial development, enyo/VirtualDataRepeater
had direct awareness of (and therefore a dependency on) Spotlight.
We now factor this out so that enyo/VirtualDataRepeater knows
nothing of Spotlight, and Spotlight itself provides a mixin
allowing Spotlight awareness to be added to VDR as needed by
library or app code.
ENYO-DCO-1.1-Signed-Off-By: Gray Norton (gray.norton@lge.com)

ENYO-1617: Factor Spotlight support out of enyo/VirtualDataRepeater

---

lib/SpriteAnimation/SpriteAnimation.js

Issue:
When we set paused as true, sprite animation is set 'paused' css by itself.
But, it is reset animation when duration is set regardless of the paused status.
Fix:
We are stop but not reset animation on _forceAnimationReset.
DCO-1.1-Signed-Off-By: Kunmyon Choi kunmyon.choi@lge.com

ENYO-1575: Fix enyo.SpriteAnimation 'paused' property

---

lib/Select.js
test/tests/Option.js
test/tests/Select.js

Options couldn't be selected using their `selected` property at create time. It was overridden by the logic in `Select.rendered()`.
Support selecting Option with selected on either Option or Select.
Added tests for Option and Select

Fixes ENYO-1553

---

lib/LightPanels/LightPanels.js

When `cacheViews` was set to `true`, we assumed that a view id would be specified. This caused some issues when the view id was not specified, resulting in erratic panel behavior.
We should not try to restore a view when the id is not specified, and should default to creating a new view instead. Additionally, we make a tweak to support the state where `cacheViews` is `false`.

ENYO-1618: Hardening to better deal with various states of cacheViews.

---

lib/LightPanels/LightPanels.js

When pushing several panels, and then returning to the first panel (index 0), navigating to the next panel (index 1) does not work when using `pushPanel` or `pushPanel`, in conjunction with the caching mechanism. This is due to the previous panels not having been popped (and properly cached) when returning to the first panel.
In `transitionFinished`, we were determining the starting index for popping based on summing the direction with the current index. If the direction jump was more than one panel, which was the case here, the starting index would be incorrect. Rather than normalizing the direction before summing, the logic has been simplified such that the starting index logic is handled by `popPanels`, which is already examining the direction. Also, removed some crufty login in …

ENYO-1590: Allow for properly popping of panels when returning to the first panel.

---

lib/LightPanels/LightPanels.css
lib/LightPanels/LightPanels.js

There was some leftover cruft from the initial implementation of `enyo.LightPanels` that utilized left/top positioning instead of translations.
The positioning has been replaced in favor of translations. Additionally, the dimension properties have been replaced with positioning properties for specifying full height and width.

ENYO-1580: Utilize translation for initial positioning.

---

source/dom/drag.js

Changes from https://github.com/enyojs/enyo/pull/1176.

ENYO-1648: Allow for combining and resetting of global holdpulse config. (2.5-upkeep)

---

.jshintrc
lib/gesture/drag.js

Previously the default holdPulseConfig would be overwritten by a call to `configureHoldPulse`, allowing no way of resetting to the default. Additionally, because the configuration was set by assignment, rather than mixed-in, the full configuration had to be specified when calling `configureHoldPulse`, rather than just the properties to override.
We now mixin the passed-in config when calling `configureHoldPulse`. Additionally, a `resetHoldPulseConfig` method has been added. Also, updated the JSHint configuration to expose `JSON` as a global var, to prevent Travis failures.

ENYO-1648: Allow for combining and resetting of global holdpulse config.

---

lib/Scrollable/Scrollable.js
lib/Scrollable/Scrollable.less
lib/Scrollable/package.json

The enyo/Scrollable mixin was previously using classnames defined
in the old scroller modules. Replacing with its own styling.

Removing enyo/Scrollable's dependency on old scroller styles

---

lib/Button/Button.js
lib/Button/ButtonAccessibilitySupport.js
lib/Checkbox/Checkbox.js
lib/Checkbox/CheckboxAccessibilitySupport.js
lib/Checkbox/package.json
lib/Input/Input.js
lib/Input/InputAccessibilitySupport.js
lib/Input/package.json
lib/Popup/Popup.js
lib/Popup/PopupAccessibilitySupport.js
lib/RichText/RichText.js
lib/RichText/RichTextAccessibilitySupport.js
lib/TextArea/TextArea.js
lib/TextArea/TextAreaAccessibilitySupport.js
lib/TextArea/package.json

Accessibility supporting for enyo UI - Button, Checkbox, Popup, Input,
TextArea, RichText
- Button: set button role and add 'aria-disabled' attribute matching
disabled property.
- Checkbox: set checkbox role and add 'aria-checked' attribute matching
checked property.
- Input: set textbox role and add 'aria-disabled' attribute matching
disabled property.
- Popup: set the 'accessibilityAlert' to read content of popup when it
is shown.
- RichText: set textbox role and 'aria-multiline' to true because
RichText supports multiline.
- TextArea: set textbox role and 'aria-multiline' to true.
At the moment RichText mixin and TextArea mixin are same, but I
separated them for maintenance.

Fixes ENYO-1638

---

source/touch/Scroller.css
source/touch/TouchScrollStrategy.js
source/touch/TransitionScrollStrategy.js
source/touch/TranslateScrollStrategy.js

Scroller contents with leading or trailing margins may not be included in the size calculations throwing off scrolling at the edges.
Add pseudo elements to scroller to force block formatting context

Fixes ENYO-1542

---

tools/deploy.js
tools/minifier/lessc.js
tools/minifier/minify.js

We allowed for the specification of the configuration options for the LESS resolution-independence plugin  programmatically, but not via the command-line.
A JSON string can now be specified with the configuration options, as the value of the `--ri` switch.

ENYO-1667: Add support for specifying resolution-independence parameters via command line.

---

tools/minifier/node_modules/less-plugin-resolution-independence/lib/resolution-independence.js

Parameter values of functions that are effectively nested in the LESS structure (in this case, they are part of other parameters) were not being converted for resolution-independence. See the ticket for more specific examples.
We've updated the `updateNode` method to effectively drill into any nested values and convert them all.

ENYO-1787: Convert nested measurement values.

---

tools/minifier/node_modules/less-plugin-resolution-independence/lib/resolution-independence.js

We were not previously allowing for falsy values when overriding resolution-independence plugin properties, such as the use of the value 0.
We now check if the property exists and use its value if so, otherwise we use the default value.

ENYO-1793: Allow for the use of falsy values when overriding parameters.

---

tools/minifier/node_modules/less-plugin-resolution-independence/lib/resolution-independence.js

Changes from https://github.com/enyojs/enyo/pull/1202.

ENYO-1793: Allow for the use of falsy values when overriding parameters. (release-2.5.3-pre.22.wb)

---

lib/AccessibilitySupport/AccessibilitySupport.js
lib/Button/ButtonAccessibilitySupport.js
lib/Checkbox/CheckboxAccessibilitySupport.js
lib/Group/GroupAccessibilitySupport.js
lib/Input/InputAccessibilitySupport.js
lib/Popup/PopupAccessibilitySupport.js
lib/RichText/RichTextAccessibilitySupport.js
lib/Table/TableAccessibilitySupport.js
lib/TableCell/TableCellAccessibilitySupport.js
lib/TableRow/TableRowAccessibilitySupport.js
lib/TextArea/TextAreaAccessibilitySupport.js
test/tests/AccessibilitySupport.js

The addition of the accessibilityDisabled property made is necessary
to consolidate the accessibility observers into a single handler so
we could toggle the values of any other property when the disabled
property changes.
Issue: ENYO-1689

Refactor accessibility property observers

---

lib/Image/Image.js

* Combine all `src` and `background-image` updates into a single method for consistent application which caught a couple edge cases where those were not updated correctly.
* Proxy `src` with `_src` so we don't overwrite the user-provided value with our error handler
* Added some docs while I was there

Refactor logic to update image src

---

tools/less.js
tools/minifier/node_modules/less-plugin-resolution-independence/lib/resolution-independence.js

There did not exist a mechanism to specify configuration options for the LESS resolution-independence plugin when the script is loaded in the browser.
As long as `less.js` is being loaded synchronously, we can parse the query string of its `src` path by examining the last script tag in the document. This *should* work for the case of `bootplate-moonstone` (and various related `bootplate` implementations) as we have control over the default implementation and how the script is being loaded. Also, cleaned up the option parsing a bit.

ENYO-1795: Enable configuration of resolution-independence plugin in browser.

---

lib/Popup/Popup.js

Both `utils` and `dispatcher` were in the global scope.
There was a typo where we had inadvertently used a semi-colon instead of a comma in a group `var` statement. The semi-colon has now been replaced with the comma.

ENYO-1832: Fix typo that caused utils and dispatcher to be in the global scope.

---

lib/BackgroundTaskManager.js
lib/SystemMonitor.js
lib/TaskManagerSupport.js

We need support for the naming of managers, so that they can be referenced in the future. Also, there is some technical debt where we have some logic for determining framerate in `BackgroundTaskManager`, which should be moved to `SystemMonitor`.
We've added a `managerName` property in `TaskManagerSupport`, and have updated `BackgroundTaskManager` to maintain a hash of names and customers. Additionally, we have moved the framerate checking logic from `BackgroundTaskManager` to `SystemMonitor`.

ENYO-1629: Add support for naming of managers. General clean-up.

---

lib/Component.js

Since the defaultKind for Component is Component itself, we need
to wait until after the constructor is defined and then assign
defaultKind on the prototype.

ENYO-1857: Fix Component.defaultKind declaration

---

lib/VerticalDelegate.js

Issue
-------
If more models are added to collection when the last page is not generated yet,  it fires error.
Cause
--------
I committed guard code to update the last page's metric which is not fully filled when we add more models. Because the last page which was not fully filled has smaller metric, so we will mis calculate a bufferSize.
However I didn't consider that the last page could not render yet. So it makes err.
Fix
----
Add guard code for the last page which is not rendered
Enyo-DCO-1.1-Signed-off-by: David Um david.um@lge.com

Enyo 1624 Allow the last page to update its metric only when it was generated before 

---

lib/UiComponent.js
test/tests/Control.js

The addition of a Flux-like data flow necessitated that we differentially update components to prevent wholesale regeneration of components each time a view was notified of a data update. A feature was needed to determine what component properties had changed and update or recreate components accordingly.
We have added an `updateComponents` method that diffs the passed-in component declarations against the previous component declarations. More specifically, values for all keys that are not in `statefulKeys`, are hashed and compared to their previous values. For the values of the keys that match those in `statefulKeys`, these values are updated on the corresponding components, on the condition that we are not in a situation where we have to regenerate the components (the non-stateful key …

ENYO-1651: Add updateComponents feature

---

lib/ContentAreaSupport.js

Rather than adding mutually exclusive properties to select between content or components, a more flexible solution would be useful.
Add ContentAreaSupport which provide a framework-level implementation for that capability.
For now, this will be limited to specific use cases -- immediately moonstone/Dialog.

Fixes ENYO-1543

---

lib/AccessibilitySupport/AccessibilitySupport.js

Though accessiblityDisabled is set to true, screen reader reads contents like moonstone checkbox icon
Screen reader reads dom node contents or aria-related attribute content like aria-label or aria-hint if accessibilityDisabled is not true. However, In the moonstone Icon, general unicode content is read out like 'checkbox' because browser supports it. 
screen reader doesn't read node with aria-hidden attribute, so we add aria-hidden with true value when accessibilityDisabled is true
Enyo-DCO-1.1-Signed-off-by: Bongsub Kim bongsub.kim@lgepartner.com

ENYO-1687 : add aria-hidden attribute for accessibilityDisabled

---

lib/resolution.js

Includes a fix for a missing `oldScrObj` which can't exist on first run.

Setup the default configuration for resolution independence support.

---

lib/LightPanels/LightPanels.js

We needed to initiate a panel index change to an existing panel, without a transition animation.
We did some refactoring and made a standard panel index change a non-animated function, and added an explicit `animateTo` function for initiating an animated panel index transition.

ENYO-1880: Add animateTo function.

---

lib/kind.js

Remove global namespace export of kind.singleton

Fixes ENYO-1677

---

lib/floatingLayer.js

Calling `focus()` on a control within the floating layer causes the browser to scroll it into view which can break things like moonstone/Popup that are designed to animate into view.
Prevent scrolling of the floating layer

Fixes ENYO-2032

---

lib/Image/Image.js

When setting the `sizing` property at component declaration time, the source is not properly set to be a background image.
We move the call to `updateSource` outside the guard for the generated state.

ENYO-2126: Always attempt to update the source, regardless of generated state.

---

lib/RepeaterChildSupport.js

The RepeaterChildSupport mixin implements a modelChanged method to
update passive bindings, but this method unintentionally overrides
any implementation of that method that may exist in the kind that
applies the mixin.
We need to have the mixin's implementation call the method
inherited from the target kind.

ENYO-2227: RepeaterChildSupport mixin shouldn't stomp modelChanged

---

lib/Scrollable/Scrollable.js

Programmatic `focus()`-ing controls causes the browser to scroll the control into view using `scrollTop` and `scrollLeft` on the nearest scrolling context ancestor that would bring it into view
Set `accessibilityPreventScroll` on controls applying enyo/Scrollable.

Fixes ENYO-2223

---

lib/LightPanels/LightPanel.js
lib/LightPanels/LightPanels.js

When panels are transitioning, panels can still be pushed, which causes undesired or unexpected behavior.
We set a `transitioning` flag and guard against pushing panels when transitioning. We also do some general clean-up and removal of cruft.

ENYO-1981: Prevent pushing panels when transitioning. General clean-up.

---

lib/LightPanels/LightPanel.js

To further decouple updating the app from updating the framework, with regard to `LightPanels`, we need to support the existing lifecycle API being used by the app.
We add some backwards-compatibility code to execute the `activated` and `deactivated` lifecycle methods.
This change is related to https://github.com/enyojs/moonstone/pull/2393.

ENYO-1981: Call activated/deactivated lifecycle methods, for now.

---

lib/DataRepeater.js

* Issue *
Selection handling in DataRepeater/DataList was inconsistent. Selections would not be properly tracked with DataList and selections were not reset when changing collections.
* Solution *
If a `selectionProperty` is defined, filter out selected items to initialize the internal `_selection` property.

ENYO-2205 Initialize selected items when collection changed

---

lib/Image/Image.css

At least in cases where the image size was not explicitly
specified and the sizing option was not being used, the placeholder
image was not properly scaled to the size of the image element.
Some simple CSS refactoring takes care of that.

ENYO-2313: In enyo/Image, ensure that placeholder image fits

---

lib/History.js

add updateHistory property to enyo/History
When false, enyo/History will only maintain its internal history stack
and will not update window.history.

Fixes ENYO-2368

---

src/Video.js

If user selects REW/FF when content is paused, setPlaybackRate should be called ahead of play.
added flag, "isNeedPlay", to make node play after setPlaybackRate  .
Enyo-DCO-1.1-Signed-off-by: Suhyung Lee (suhyung2.lee@lge.com)

ENYO-1725: enyo.Video: setPlaybackRate should be called ahead of play in a certain case

---

src/LightPanels/LightPanel.js
src/LightPanels/LightPanels.css
src/LightPanels/LightPanels.js
src/ViewPreloadSupport.js

When changing panel indices, we had been transitioning the previous and current panels individually, and this caused some visual glitches on slower processors. Additionally, it seemed that the transition logic could be made more efficient if we transitioned a single element.
We have wrapped the transitioning panels in a container and transition the container, instead. This allowed for some clean-up and simplification of the transition logic. Lastly, we have also removed the backward-compatibility calls for `activated` and `deactivated`, as those were deprecated.

ENYO-2384: Use panel container wrapper for panels.

---

src/LightPanels/LightPanels.css
src/LightPanels/LightPanels.js

I missed this when refactoring the `LightPanels` animation logic, and it was an edge case not easily seen with the samples. The refactoring work exposed a latent issue where we were passing the wrong value for the `animate` property to the `shiftContainer` method.
We have updated some of the logic so that the semantics are more consistent, and are now passing the correct value for the `animate` property. I also threw in some tweaks for animation logic, and fixed a bug that was introduced by moving to a panel container structure.

ENYO-2421: Prevent animating a direct transition.

---

src/DataRepeater.js

POJO selection not working because bindings do not update when we change the underlying selection property
Call the `syncBindings()` method on the row when we update the selection property

ENYO-2257 DataList/DataRepeater does not update selection with POJOs

---

src/LightPanels/LightPanels.js

notify observers of index when using LightPanels.animateTo
Without the notification, the aria observer cannot update the role of
the active LightPanel.

Fixes ENYO-1994

---

src/UiComponent.js

Failing unit test for ViewController was due to cached bubbleTarget not being cleared when live-view swapping.
Ensure we scrub the cached bubble targets when necessary. Note that this functionality is currently only ever used by ViewController and no implementations using this are known.
Enyo-DCO-1.1-Signed-Off-By: Cole Davis (cole.davis@lge.com)

Fix for: ENYO-2459

---

src/Drawer.js

When tearing down a view that is to-be-cached, animations can be interrupted and leave the view in an in-between state that causes problems when restoring the view.
In `teardownRender`, we force the animation to complete if we are caching the view.

ENYO-2444: Complete animation when tearing down a cached view.

---

src/AccessibilitySupport/AccessibilitySupport.js

Rather than forcing a tabindex of 0 for any control with content or
aria-label, add the tabIndex property which maps to the tabindex
attribute. This will allow saner keyboard navigation rather than
virtually everything being navigable via tab.

Fixes ENYO-2430

---

src/TouchScrollStrategy.js

Enyo-DCO-1.1-Signed-off-by: Jason Robitaille <jason.robitaille@lge.com>

ENYO-2504: TouchScrollStrategy should require touch.js

---

src/LightPanels/LightPanels.js

If the main loop is very busy, such as when we are rapidly switching panel indices, the delay between setting up the initial position of the panel container, and applying the transition to animate this panel container is small enough that the style change is batched and there is no transition. This causes a number of issues, such as lack of a visible animation, and more importantly, the `transitionFinished` handler for the `ontransitionend` event is not fired.
We moved the class application for the initial panel container position and individual panels into a rAF callback, and also moved the call to apply the transition styles into a rAF callback as well, so that we take these calls off of the main loop. Additionally, we placed the panel container in a compositing layer if `animate` is …

ENYO-2491: Ensure that panel transition runs.

---

src/Control/Control.js
src/Layout.js

Reflowing a Control when it's hidden generally doesn't make sense,
since a) it's wasteful to spend cycles laying out something that
can't be seen; and b) the layout may depend on measuring the
Control's children, and they can't be accurately measured if
they're not showing.
We therefore defer reflow in the case where we're hidden, and
wait until we're shown.
In the case where we are explicitly hidden (i.e., `showing` is
`false`), we defer immediately. We can't inexpensively detect the
case where we're showing but an ancestor is hidden, so to handle
that case we rely on the layout to do its measurements and let
us know (by returning `true`) if we need to reflow again the next
time we are shown.

ENYO-2258: Defer reflow when hidden, do it when shown

---

src/VirtualDataRepeater.js

VirtualDataRepeater has, until now, routinely made refresh() an
async operation. This behavior was inherited (via copy/paste) from
DataRepeater when VDR was first created.
It's not apparent that making refresh() async is necessary or
useful for VDR, and the async operation is causing problems in at
least one instance -- specifically, when the data underlying a
NewDataList is modified while the list is hidden, the list isn't
refreshed until the list is reshown, and at that time the "old"
list contents flash momentarily before being refreshed.
We address this issue by making refresh() synchronous for VDR and
its subkinds.

ENYO-2514: VDR: Always refresh immediately

---

src/LightPanels/LightPanels.js

When initially populating a `LightPanels` kind, if `pushPanels` is used, by default the index is set to be the index of the last panel pushed. If we attempt to set the index to a different value, immediately after this operation, the `ontransitionend` event for the must recent index change does not always fire, especially on slower hardware, as the rAF operation effectively batched both the transition setup and the transition application as the 16ms timeout is not sufficient during what is presumably some heavy load (executing the previous transition), resulting in no transition event occurring at all.
To counter this, we separate out the two operations into different rAF requests, and kick off the transition application rAF *after* the transition setup rAF. This way there is a redraw …

ENYO-2536: Guard against initialization edge cases

---

src/NewDataList.js

In `NewDataList`, the logic for constraining the minimum scroll
threshold value was susceptible to failure in the case where the
values being compared were long floating point values (we were
checking for equality, but in the failure case two values that were
"conceptually equal" for the purpose of our algorithm were actually
different in digits far to the right of the decimal). We replace
the equality operator  with a call to `Math.min()` to constrain the
threshold  value, which gives us the desired result.

ENYO-2565: Bullet-proof logic for constraining min threshold

---

src/ViewPreloadSupport.js

We had previously assumed that by mixing in the `ViewPreloadSupport` mixin, views would always be cached. Now that we are exploring the application of this mixin to other kinds where view caching can be disabled in certain cases, this property has to be settable.
We now check for the existence of the property (i.e. defined on the kind we're being mixed into), otherwise we default to a value of `true`.

PLAT-6855: Allow overriding of cacheViews property.

---

src/Control/Control.js
src/LightPanels/LightPanels.js
src/LightPanels/LightPanels.less
src/Popup/Popup.js
src/ViewPreloadSupport.js

1) enyo LightPanelsSample is not displayed on safari browser. Below error is occured.
Error: TypeError: 'undefined' is not a function (evaluating 'global.requestAnimationFrame(fnSetupClasses)')
2) When animate is true, LightPanelsSample does not animation work on safari browser.
3) When cache is true, LightPanelsSample does not work on safari browser. Below error is occured.
TypeError: 'undefined' is not a function (evaluating 'view.node.remove()')
4) ontransition event callback is not called on safari browser. 
1) window.requestAnimationFrame function does not exist on safari browser
2) In LightPanels.less, safari does not support transform property
3) safari does not support dom node's remove() function.
4) safari does not support ontransition event. 
1) enyo animation module provides …

PLAT-8119: Add or modify transition related functions for safari browser

---

src/LightPanels/LightPanels.js

Due to some specific use cases, there was a need to navigate to a panel that is effectively a "sibling" of the current panel, meaning that they share the same ancestor and we wish to maintain this panel hierarchy / ordering. Popping the current panel and pushing the sibling panel exposed a small time window where the ancestor panel could be momentarily spotted, but was immediately torn down as the sibling panel was pushed. As `Spotlight` was still processing events, it was attempting to utilize a null node reference in these cases.
We have added a general `replaceAt` method to `LightPanels` that will replace panel(s) in-place and allow for changing to a "sibling" panel.
I also added an additional commit to undefer panel purging. Let me know if it makes more sense to kick this out to …

ENYO-2592: Add replaceAt method.

---

src/LightPanels/LightPanels.js

We had previously set the animation direction to be the same in both RTL and LTR to support UX requirements. Because we are using this kind in `VideoPlayer`, we want to support reversing the animation direction in RTL.
We have added a `reverseForRtl` property that reverses the animation direction if this is `true` and we are in RTL, and applies only to a horizontal orientation.

ENYO-2556: Allow for reversing animation in RTL.

---

src/LightPanels/LightPanels.less

We had originally set `direction:ltr` for the `enyo-light-panels` class in order to preserve the position of the of the container when in an RTL locale, so that we did not need to recompute transition percentages. This had a side effect of incorrectly setting the directionality to `ltr` for panel contents, when in an RTL locale.
We have added an additional rule to explicitly set `direction:rtl` for panel contents when in an RTL locale.

ENYO-2625: Prevent overriding of panel content directionality.

---

src/Video.js

The Video component would not always successfully start playing the
video after a rewind operation.
This problem was, at least in part, caused by the need to emulate rewind
on platforms that don't support negative `playbackRate`s.  Additionally,
a problem was discovered with handling the switch between slow and
fastForward. The slowForward playback rate array was updated to remove
the rate of '1' (normal speed) and the fastforward mechanism is updated
to move to play when reaching the end of the playback rate array
(Previously, it rotated to the fast forward array after playing the '1'
rate). There should be no change for apps that did not alter the
playback rate array. The player has also been updated so that rewinding
after a slowForward will now result in a slowRewind. The converse …

ENYO-2416 Fix issues with VideoPlayer

---

src/UiComponent.js

Some time ago, we added some logic to prevent resize events from
waterfalling through hidden UI components. The intention was to
prevent unnecessary layout from happening.
This approach generally worked, but there were some problem cases,
as noted in a comment that went in with the original change.
Specifically, a component that is hidden and therefore never
receives a resize event has no way of "knowing" that a resize has
been requested, so won't reflow its layout when it is later shown.
We recently added some different but related logic to allow
components to defer reflows when hidden and perform them later upon
being shown. This newer mechanism has the advantage of avoiding the
problem described above.
Since the expensive part of dealing with a resize event is almost
always performing …

ENYO-2557: Allow resize events to waterfall freely

---

src/LightPanels/LightPanels.js

The `popOnForward` API does not really make sense and is not a use case that has actually come up, with the use of `cacheViews`, so it should be removed to avoid confusion and tighten up our APIs.
The property has been removed and the logic has been updated and cleaned-up to reflect this.

ENYO-2541: Remove popOnForward.

---

src/History.js

There isn't a way to prevent the back key from popping the current history entry, so we are re-pushing a dropped entry in these cases. If the back key is pressed repeatedly (particularly on slow hardware), the queue can become out of sync and cause `enyo/History` to be in a state where future back key presses do nothing.
We use a `while` loop to account for the case where the queue is modified while it is being iterated through.

ENYO-2667: Account for queue being modified during iteration.

---

src/NewDataList.js
src/Scrollable/Scrollable.js

enyo/Scrollable provides a `scrollToControl()` method that
has a generalized implementation for calculating a Control's
position and scrolling to it.
In the case of enyo/NewDataList, it's possible to provide an
alternative implementation that is more performant and more
accurate (more performant because it doesn't need to query the DOM
for bounds, more accurate because the generalized implementation
is influenced by current scroll position and may give slightly
different values when animating vs. not).
We tweak enyo/Scrollable to defer to an alternative method when one
is provided, and we provide an alternative method in
enyo/NewDataList.

ENYO-2644: Override scrollToControl() in enyo/NewDataList

---

src/LightPanels/LightPanels.less

When restoring a cached view that performs bounds calculations during an initialization lifecycle method, such as `rendered`, the bounds of the component will be zero as we are using `display:none` to hide offscreen panels. In the case of `moonstone/Scroller`, the bounds of zero resulted in the paging controls not being properly updated/enabled when the view was restored.
As we want to hide any potentially offscreen panels (i.e. in use cases where this is not being used full-screen or we don't want to clip the overflow) but want to maintain the proper bounds values, we instead use `visibility:none` for offscreen panels.

ENYO-2673: Prevent bounds of zero when restoring a cached view.

---

src/TranslateScrollStrategy.js

When re-rendering a scrolled scroller using TranslateScrollStrategy
with translateOptimized: true, the startX/Y values would be updated to
be a non-zero value matching the prior values of scrollLeft/Top.
However, the scrollNode was also translated the same amounts. As a
result, when the user scrolled, the content would jump the amount of
startX/Y resulting in whitespace above the content.
Since the purpose of startX/Y is to offset the transform the amount of
the scrollLeft/Top of the scrollNode but those values are never
updated with translateOptimized: true, we'll reset them to 0 in
rendered() so no offsetting occurs.

Fixes ENYO-2691

---

src/History.js

When `clear()` is called when one or more `drop()` is being queued, length of `_history` array does not reflect the correct number of history entities to clear and ends up dropping more than it needs to. This results in splicing the `_history` array with negative starting index when processing the enqueued pop.
Clear function would remove all entities in `_history` as well as the `_queue`.

ENYO-2698: Reset queue and history instead of enqueueing drop when clearing history

---

src/LightPanels/LightPanels.js

When replaceAt() goes through the loop to remove panels, removePanel changes the length and entries of panels array. This will skip every even numbered index of panels that needs to be removed.
Remove panel in reverse order.

ENYO-2719: Remove panel in reverse order when replacing panels

---

src/NewDataList.js
src/VirtualDataRepeater.js

This change moves the logic governing deferred refresh() and reset() behavior up the inheritance chain from NewDataList to VirtualDataRepeater and reintroduces async refresh for performance reasons.
In the process, it addresses ENYO-2533 and ENYO-2696, and replace the original fix for ENYO-2514.
See the notes on the individual commits for more detail.

ENYO-2533, ENYO-2696, ENYO-2514: Overhaul refresh / reset in VDR, NewDataList

---

src/VirtualDataRepeater.js

In `reset`, the value of the `visibility` property was not being set to a valid value, and so in certain cases the list remained hidden.
We set the value to `visible` when we want the list to be shown.

ENYO-2768: Set visibility to a valid property value.

---

src/Image/Image.js

The placeholder feature in enyo/Image currently has logic to
remove the placeholder when the image itself loads.
This logic was intended to provide support for images that contain
transparent or semi-transparent pixels, by preventing the
placeholder from "showing through" those pixels.
However, supporting this use case can cause expensive style
recalculation under some circumstances -- specifically, it was
causing grid list regeneration on mid-range TV hardware (M16) to be
half a second slower.
Since the 80+% use case for placeholder images involves traditional
opaque, rectangular images, we'll simply remove the sometimes-
expensive logic and document the limitation. We can consider
reintroducing placeholder support for transparent images at some
future point, either with a flag to …

ENYO-2734: Remove transparent-image placeholder support

---

src/Control/Control.js
src/DataList/DataList.js
src/HTMLStringDelegate.js
src/VerticalDelegate.js
src/ViewPreloadSupport.js
src/dom.js

We have recently started getting more aggressive about view
virtualization for performance reasons. One tactic in this area
involves tearing down the DOM representation of a Control and then
restoring it later as needed ("view caching").
In the case where the view being cached / restored contains a
DataList, the state of the view was not being preserved as expected
because DataList effectively resets upon being (re-)rendered.
The proper fix for this issue would involve rethinking the DataList
lifecycle with view-virtualization scenarios in mind, but this
would be a significant effort and the current DataList is on a
relatively short road to replacement, so for now we'll go with a
lighter-weight, Moonstone-specific solution.
That solution does, however, require a number of minor tweaks and …

ENYO-2744: Tweaks to allow restoration of list state on render

---

src/SystemMonitor.js

The system idleness monitor was overly idealistic by checking user input (mouse movement, keypresses). In real-world use cases, the user will continue to move the mouse, and prevents the system from ever registering as "idle." Kinds that rely on idleness, such as the `BackgroundTaskManager`, can encounter this scenario and not be able to process tasks, for example.
We have added an internal flag to control the monitoring of these user input signals, `monitorUserInput`. This is set to `false` by default as we want to primarily rely on the system load check for idleness determination (processing background tasks, for example, while the user is moving the mouse and/or pressing keys, is not undesired). We may want to use these user input signals down the road, but they are effectively being …

ENYO-2780: Disable user input monitoring, by default.

---

src/Control/Control.js
src/HTMLStringDelegate.js

In the fix for ENYO-2744, we made a tweak to the interface between
enyo/Control and enyo/HTMLStringDelegate to make it possible for
Controls to override `teardownChildren()`. In doing so, we failed
to preserve the `cache` argument to `teardownChildren()`, which
caused a regression for Controls that use the 'renderOnShow'
feature.
This regression could have been addressed by simply making sure we
passed the `cache` argument properly, but on further reflection it
seems safer and more future-proof to instead revert the previous
change in favor of an explicit `beforeTeardown()` lifecycle method
that Controls can implement as needed. Doing that now.

ENYO-2788: Provide an explicit `beforeTeardown()` hook for Control

---

src/AccessibilitySupport/AccessibilitySupport.js

The `accessibilityPreventScroll` feature prevents the browser
engine from doing bad auto-scrolling things when an item is focused
in one of our scrollers. It works by listening for native scroll
events and forcibly resetting native scrollTop and scrollLeft
properties as needed.
Our logic for resetting scrollLeft did not previously account for
RTL, so we fix that.
As noted inline, the current fix is specific to Blink and WebKit;
we'll need to do something clever to make this work cross-browser,
but not attempting that now because cross-browser support is not
urgent for the imminent internal release, and this is not our only
cross-browser scrolling issue. Wrote up ENYO-2841 to track future
work.

ENYO-2840: Make `accessibilityPreventScroll` work in RTL

---

src/VirtualDataRepeater.js

It has taken a few tries, but I think this finally gets us to the
bullet-proof child-indexing solution we've been chasing.
We simply rebuild the index from scratch each time we run the
virtualization logic in doIt().

ENYO-2816: Fix VDR child indexing logic (again)

---

src/DataRepeater.js
src/NewDataList.js
src/ScrollMath.js
src/Scrollable/Scrollable.js

The logic for scrolling to a child of Scrollable has until now
been essentially monolithic, but we now refactor it to allow parts
of the logic to be selectively overridden.
Specifically, there are now separate methods for getting the
offset coordinates of the child (`getChildOffsets()`), calculating
the target scroll coordinates (`getTargetCoordinates()`), and
actually effecting the scroll (`scrollToTarget()`).
The immediate use case is to provide a custom implementation of
`getChildOffsets()` for NewDataList, since NewDataList can get
child offsets more efficiently than the default implemenation does,
and can also properly account for the spacing of list items in its
own implementation. (Not properly accounting for spacing was the
actual root cause of ENYO-2644 and ENYO-2783, the issues …

ENYO-2783: Refactoring in enyo/Scrollable to allow customization

---

src/ViewLayout/ViewLayout.js
src/ViewManager/ViewManager.js

Added opts parameter to several methods to allow one-time activation
configuration (e.g. disabling animation for hiding a floating panel).

Fixes PLAT-11951

---

src/DataList/DataList.js

reset absoluteShowing when DataList is tore down

Fixes PLAT-13387

---

src/Popup/Popup.js

When an `enyo/Popup` is showing, and something triggers its destruction (i.e. destroying and recreating client controls), if a scrim was displayed, it will remain on-screen, preventing further interaction with the app.
Now upon destruction, we remove the scrim if the popup is showing.

ENYO-2604: Remove scrim upon destruction.

---

src/FluxStore.js

The `data` object was being shared by all subkinds of `FluxStore`.
We instantiate the `data` object in `create`.

ENYO-2027: Prevent shared data object.

---

src/DataRepeater.js
src/logger.js

The name of the logger module had been incorrectly set as `enyo/logging`.
The module name has been updated to `enyo/logger` and any associated links have been updated accordingly.

ENYO-2993: Use correct module name.

---

src/platform.js

There are a subset of Android devices using the Android browser (version 2 to 4) that have the userAgent string pattern `Android/4.x.x`, which was not being detected by our current pattern (expecting `Android 4.x.x`).
We cherry-picked @wangii's changes and combined the patterns into a single pattern for detecting Android 2-4 devices.

ENYO-896: Combine Android detection patterns.

---

src/dom.js

Visual Studio outputs an error when packaging a Windows 10 enyo application.
Validate that a method exists before firing, as Windows 10 removes the Windows 8 method and requirement of using `MSApp.execUnsafeLocalFunction` to set innerHTML content.
Enyo-DCO-1.1-Signed-off-by: Jeremy Thomas <jeremy.thomas@lge.com>

ENYO-2409: Fix Windows 10 app deployment error

---

src/UiComponent.js

The owner might need to be explicitly specified when using `updateComponents`, and this is not currently supported.
An additional parameter representing the default components properties has been added to `updateComponents`; these properties are not considered as part of component diffing. Additionally, we have added an options parameter that currently has a single configurable property that specifies whether or not component property updates should be made directly (in case we want to update values, but not fire off any change handlers), or via the generic setter (this is the default behavior). Lastly, renamed some local variables.

ENYO-2621: Add support for specifying default component properties.

---

src/dom.js

Visual Studio outputs an error when packaging a Windows 10 enyo application.
Validate that a method exists before firing, as Windows 10 removes the Windows 8 method and requirement of using `MSApp.execUnsafeLocalFunction` to set innerHTML content.
Enyo-DCO-1.1-Signed-off-by: Jeremy Thomas <jeremy.thomas@lge.com>

ENYO-2409: Fix Windows 10 app deployment/innerHTML issue

---

src/gesture/drag.js

If endHold() is called during a hold event handlers, this._unsent will
be nulled which causes an exception because it is assumed to be an
array. Adding a truthy guard to ensure that the next event is only
shifted if it hasn't been cleared.

Fixes ENYO-3038

---

src/ViewManager/ViewManager.js

With nested ViewManagers, stopping propagation of dragstart from an
interior ViewManager would prevent the parent from resetting its drag
state. The consequence is that a previously set dragView in the parent
would be tore down when an invalid view drag happened in the child VM.

Fixes ENYO-30307 allow dragstart to propagate from ViewManager

---

src/LightPanels/LightPanels.js

When calling `animateTo` sequentially, we can end up in a state where the currently active panel is positioned incorrectly, as the state used to setup the transitions for the second call to `animateTo` can reflect the state before the first call to `animateTo` has completed.
If we have initiated a transition, we prevent any subsequent transitions from being processed. This seemed like the safest fix, though any logic that leads to multiple, sequential calls to `animateTo` would need to be tweaked and/or re-examined in the app as there should be a better way to achieve the same results. This mainly came up because of an edge case scenario in the application where this sequence of events occurred (we had previously guarded `next` and `previous`, but this scenario seems to be a result of …

ENYO-2913: Prevent concurrent transitions when setupTransitions is triggered via an index change or animateTo call.

---

src/ViewLayout/ViewLayout.js

There are a couple scenarios in which a transition might not complete
before another is registered possibly causing layout completion
activities to be skipped. To avoid this, mark any incomplete
transitions complete so the callback can fire to clean up before
registering the new transition.

Fixes ENYO-3071

---

src/Scrollable/Scrollable.js

`enyo/Scrollable` has a `calcBoundaries()` method that it uses
internally and exposes publicly to ensure that a scrollable Control
stays up to date with respect to its own size and the size of its
contents.
In this change, we add a call to `calcBoundaries()` when the
scrollable Control is shown to ensure the boundaries are correct,
taking into account any changes that may have occurred while the
Control was hidden.
This change was prompted by ENYO-3049, in which the scroll
boundaries and position were inaccurate after hiding NewDataList,
removing items from its backing collection, and then re-showing
the list.
We chose this simple fix over more complicated alternatives,
including deferring calls to `calcBoundaries()` when the
scrollable Control was hidden and then calling it only when …

ENYO-3049: Calculate bounds when shown

---

src/History.js

There are certain cases where a browser pop can be queued (such as popping the last entry on the stack, whose handler triggers a subsequent pop, and expects the browser to go back). Specifically, this occurs in the case of enyo-strawman, which relies on browser back to return from samples to the main list, but can occur in other apps that rely on browser history.
We have relaxed the guard code in `handlePop` so that we clear the queue in this case, effectively moving this guard to `processState` as there will be no pop handler for this browser back entry.

PLAT-15389: Allow for clearing of queue for pops without a corresponding history entry.

---

src/LightPanels/LightPanels.js
src/ViewPreloadSupport.js

There were a few issues when disabling `cacheViews`, namely related to the panel lifecycle methods that assumed that certain components were still instantiated (primarily in the `moonstone/LightPanels` case), which caused null reference errors as the panel had already been destroyed.
There were a number of tweaks that had to be made to support destruction of panels, as this was not a primary use case and the related logic for this mode had gotten out of sync.
- The post-transition logic has been adjusted:
- Instead of only executing the `postTransition` method of a panel asynchronously, we are now asynchronously executing the entirety of the post-transition work, including `postTransition` and panel removal. Unfortunately, there is still a performance issue if `postTransition` is not made …

PLAT-15150: Fix issues with destruction.

---

src/LightPanels/LightPanels.js

There are certain circumstances where a developer will need to check whether or not `LightPanels` is currently transitioning, but the property is private. We have safeguards against performing any adverse actions while transitioning, but we can provide something for developers to check.
We have exposed a public method to determine the transitioning state.

ENYO-2951: Expose transitioning property via a public method.

---

src/ShowingTransitionSupport.js

Squashed commit history
Take advantage of utils.call, and don't double-bind-safely.
Docs update, and moving control to WIP.
Fixup docs
Adding a default for shownClass simplifies the usage a bit in many cases.
Added support for methods to be called out of immediate scope, and hardening of unexpected duration changes.
ENYO-2718: Update caching of shown and hidden method scopes.
ENYO-2718: Re-add variable assignment for proper module documentation.
Methods should run even if there's no duration
Normalized the order of the method execution …

ENYO-2718: Added ShowingTransitionSupport, a mixin to make showing/hiding animations easier.

---

src/LightPanels/LightPanels.js

When a transitioning element is hidden, the `ontransitionend` event is never fired (https://bugs.webkit.org/show_bug.cgi?id=51945). In the case of `LightPanels`, this prevents some necessary post-transition clean-up that is executed as a result of handling this event.
We have added some fallback logic that directly executes the clean-up logic, if it has not already been executed for the current transition. An alternative, and arguably more direct solution, could be to execute the clean-up logic whenever the panels instance is hidden (https://github.com/enyojs/enyo/compare/2.6.0-dev...ENYO-3011-aarontam-1). This works well for the current case and the specific behavior of hiding transitioning elements, but it seemed safer to have a catch-all to handle any other edge cases and quirks we may …

ENYO-3011: Ensure that transition clean-up logic is always executed.

---

src/LightPanels/LightPanels.js

When using `replaceAt`, we weren't doing anything intelligent with respect to the destination index, after the replacement had completed. This could result in being left with a panel-less display (not a TV panel, mind you).
We have added options support to `replaceAt`, which takes in the same options set as `pushPanel`/`pushPanels` for consistency. We are only concerned with `targetIndex` for the time being, which is used if specified, otherwise the first replacement panel will become the destination panel, after the replacement.

ENYO-3098: Switch to a logical panel after replacement occurs.

---

src/platform.js

Certain platforms will return an incorrect platform touch/gesture value, due to a recent change. 
As this issue was introduced after adding specific IE-Edge browser support, we need to verify that only Edge/IE are affected by the new conditional(s) to check touch/gesture support. IE9 does not support touch, so we don't worry about that.
Gesture Support
IE10, IE11, and Edge all support the proprietary `onmsgesturestart` event, so we can simply check for this to determine MS gesture support.
Touch Support
IE10 supports the already-in-use `msMaxTouchPoints` property and Edge/IE11 support `msManipulationViewsEnabled` and `maxTouchPoints`, both which return the touch manipulation ability and if touch points are available.
Enyo-DCO-1.1-Signed-off-by: Jeremy Thomas <jeremy.thomas@lge.com>

ENYO-3130: Touch/gesture fix

---

src/Source.js

Squashed changes from https://github.com/enyojs/enyo/pull/1357.
ENYO-1998: Return array of results in case of multiple sources
ENYO-1998: Remove forEach and cleanup

ENYO-1998: Return source action result on execute

---

src/touch.js

Issue
------
: Forced reflow occurs when document.elementFromPoint called
Fix
------
: Fixed event target during 'touchmove'
https://jira2.lgsvl.com/browse/PLAT-17001
Enyo-DCO-1.1-Signed-off-by: Mikyung Kim <mikyung27.kim@lge.com>

PLAT-17001: Removed forced recalculate

---

src/RichText/RichText.js

For the `enyo/RichText` control, we had been utilizing some unstable and non-standard APIs (specifically, selection modify) for handling cursor movement, and other selection modification operations. This does not work across different platforms and we should not be promoting the use of these APIs.
We have deprecated 4 methods which effectively called one another successively. I realize that `moonstone/RichText` is utilizing `moveCursorToEnd`, which works currently as Moonstone is targeting WebKit platforms, but it seemed repetitive to copy over this functionality to `moonstone/RichText` currently. If and when we actually remove the `moveCursorToEnd` API, we can consider porting this functionality to `moonstone/RichText`, or go another direction with the implementation. …

ENYO-3174: Deprecate unstable APIs.

---

src/Media.js
src/Video.js

We had previously been providing a `srcElement` property for our generated media events. This is more of an optional change, and we are not utilizing this property anywhere internally, but in the spirit of being more standards-compliant and consistent, we should move away from this.
We have removed the `srcElement` property when generating media events.

ENYO-3184: Remove srcElement property for generated media events.

---

src/ViewController.js

If `enyo/Control` is never required in an application, the default kind becomes `enyo/Component` instead.
We explicitly require `enyo/Control` in `enyo/ViewController`.

ENYO-3164: Make Control be the default kind.

---

src/HTMLStringDelegate.js
src/VerticalDelegate.js

Issue
------
: When swapping pages while scrolling a list, it took long time to tear down and regenerate page DOM elements.
: This is POC
Fix
------
: I avoided to tear down and regenerate page DOM elements while scrolling a list.
Enyo-DCO-1.1-Signed-off-by: YB Sung <yb.sung@lge.com>

PLAT-16999: Avoid to tear down and regenerate page DOM elements while scrolling a list

---

src/Control/Control.js
src/ScrollMath.js
src/touch.js

Issue
------
: We need to reduce JS execution time to handle touchmove and to update DOM element while scrolling a list.
Fix
------
: I applied rAF into not enyo/ScrollMath.animate.fn() but enyo/Control.applyStyle() and called enyo/ScrollMath.animate.fn() directly when handing "touchmove" event.
Enyo-DCO-1.1-Signed-off-by: YB Sung <yb.sung@lge.com>

PLAT-17000: Apply rAF into Control.applyStyle

---

src/Select.js
test/tests/Select.js

Fixes ENYO-3204 adds guard for setting the value of a select box in <= IE11

---

src/dom.js

IE11 doesn't support node.remove() and the test for it fails for
<select> elements which do have a remove method for another purpose.
Since remove() is effectively just sugar, we remove it to ensure
compatibility.

Fixes ENYO-3208

---

src/Animator.js
src/Loop.js
src/ScrollMath.js
src/ViewManager/ViewManager.js
src/animation.js

Web engines such as Mozilla do not support `cancelRequestAnimationFrame`, and instead support the more-standard `cancelAnimationFrame`.
Aside from some minor refactoring, we have provided support for either `cancelRequestAnimationFrame` or `cancelAnimationFrame` as older WebKit only supported `cancelRequestAnimationFrame`. Additionally, we have updated our animation API to provide a `cancelAnimationFrame` method and have deprecated the previous `cancelRequestAnimationFrame` method, in the name of consistency with the standard animation API. Also, considered having the deprecated `cancelRequestAnimationFrame` method call `cancelAnimationFrame`, but decided against it as the method effectively calls a single method itself.

ENYO-3222: Adding support for cancelAnimationFrame.

---

src/gesture/gesture.js

For environments where we are using a trackpad for scrolling, as opposed to a standard scroll wheel, there are issues with scrolling in Firefox, specifically when using a non-native scroller (i.e. Moonstone scroller, which relies on the value of the `wheelDeltaY` event property).
In short, handling mouse wheel events is broken and incomplete as a web standard, currently.
The `mousewheel` event we are currently handling is deprecated and not supported at all in Firefox. I had initially implemented a version of the cross-browser mouse wheel handling as recommended by MDN (https://developer.mozilla.org/en-US/docs/Web/Events/wheel#Listening_to_this_event_across_browser), but the current, standard `wheel` event does not handle scroll inversion and provides no way to detect or account for this …

ENYO-3210: Added better support for trackpad scrolling in Firefox.

---

src/NewDataList.js

If a list is scrolled to the end and the size of the collection
changes, we need to recalculate the scroll thresholds and possibly
adjust the range of items to be rendered.
Until now, we've only adjusted thresholds in the `scroll()` method,
based on the direction and distance we've scrolled. In this fix, we
add a new method, `refreshThresholds()`, which recalculates the
thresholds based on the current scroll value. We call the new
method from `modelsAdded()` and `modelsRemoved()` to make sure that
the thresholds and item range are correct after the size of the
collection has changed.

ENYO-3219: Refresh scroll thresholds when adding / removing models

---

src/NewThumb/NewThumb.js

Issue:
NewThumb is measure bounds of its parent on render time to determine
minSizeRatio and naturalSize. If list is initially hidden and show
later, these metrics are not updated.
Fix:
Call calculateMetrics in showingChangedHandler on showing.
Enyo-DCO-1.1-Signed-off-by: Kunmyon Choi kunmyon.choi@lge.com

ENYO-3227: Recalculate metrics on showing

---

src/NewThumb/NewThumb.js

Issue:
NewThumb is created from scratch to support new smart share use case. Now we have new use case of resize the new data list at runtime. And, current version of scroll thumb doesn't include that logic.
Fix:
Recalculate metrics on resize handler. So that it can draw itself in correct size and position.
Enyo-DCO-1.1-Signed-Off-By: Kunmyon Choi (kunmyon.choi@lge.com)

ENYO-3138: Recalculate scroll thumb metrics on resize

---

src/VerticalDelegate.js
src/VerticalGridDelegate.js

We use page concept on DataList and DataGridList. When item count is not devided by controls per page, last page can have different page height from others. The adjustBuffer function of VerticalDelegate and VerticalGridDelegate calculate buffer size by accumulating page size. But, we use default page size when the page is not generated yet. So, the buffer size is different between before and after generating the last page.
Calculate buffer size based on item size and item collection length instead of page size and page height. And divide item collection length by number of columns in case of GridList.
Enyo-DCO-1.1-Signed-off-by: Kunmyon Choi kunmyon.choi@lge.com

ENYO-3158: Adjust Buffer size based on item size and count

---

src/LightPanels/LightPanels.less

Issue:
LightPanel is set visibility: hidden; on offscreen panel.
When element like checkbox is have visibility: visible; inside of
panel, then it will be shown even if panel is hidden. In popOnBack
case, check mark shown at the end of transition shortly. But, in
static panels case the check mark will be shown permenently.
Fix:
We apply opacity: 0; also to effectively hide all the children and
also not loosing the ability of blocking event and tap index handle.

ENYO-3333: apply opacity 0 on off screen light panel

---

src/NewDataList.js

The recently added `refreshThresholds()` method was not properly
constraining the calculated threshold values in some cases. In this
change, we fix that oversight.
At the same time, we refactor `scroll()` to replace its own
threshold logic with the logic in `refreshThresholds()`, since the
old logic has become redundant.

ENYO-3219: Contrain values produced by `refreshThresholds()`

---

src/ViewManager/ViewManager.js

Issue
------
: To update swapbuffer when dragging a panel in enyo/ViewManager, we need 1 touchstart event and 2 touchmove event ( One for dragstart, the other for drag ) because enyo/ViewManager actually move a panel with "drag" event.
Fix
------
: I called "drag" event handler ( enyo/ViewManager.handleDrag) in "dragstart" event handler (enyo/ViewManager.handleDragStart) so that enyo/ViewManager could move a panel with "dragstart" event. 
After fixing, I could reduce the minimum time from QPA touch to swap buffer update.
JIRA  | PLAT-21046 garnet/PanelManagerSample | PLAT-21057 garnet/ContextualPanelSample
------------ | ------------ | -------------
default | 135ms  | 143ms
Call "drag" event handler | 113ms  | 91ms
https://jira2.lgsvl.com/browse/PLAT-21046 …

PLAT-21046: Reduce the time from QPA touch to swap buffer update

---

src/AccessibilitySupport/AccessibilitySupport.js

The accessibilityPreHint is neccessary for reading a hint message before
control's content or aria-lable.
https://jira2.lgsvl.com/browse/ENYO-3326
Enyo-DCO-1.1-Signed-off-by: Bongsub Kim <bongsub.kim@lgepartner.com>
Change-Id: I6a1bf16799c415ba4f153420530e43fc75614e9d

ENYO-3326: Support accessibilityPreHint

---

src/NewDataList.js

In guard5way(), we used _last value as a limit condition.
However, _last value wasn't updated as our expectation and we couldn't guard
5way correctly.
Enyo-DCO-1.1-Signed-off-by: Yeram Choi yeram.choi@lge.com

ENYO-3375: Re-calculate _last when refreshThreshold is executed

---

src/ShowingTransitionSupport.js

When we apply showingTransitionSupport on control, it is hard to hook
before showing start timing from app side. This is because the showing
changed handler is calling super call when animation ends.
We add showingMethod and hidingMethod api to support this case.

ENYO-3382: Add support showing and hiding method to transition support

---

src/ShowingTransitionSupport.js

Job should be executed although control is destroy.
Enyo-DCO-1.1-Signed-off-by: Yeram Choi (yeram.choi@lge.com)

ENYO-3411: Clear job function in case of destroy

---

src/dom.js
src/resolution.js

This change includes:
* PLAT-23332 #1455 
* Dynamic application of the base font size on the document object. No longer reliant on external CSS.
* A new enyo/dom method: removeBodyClasses
* RI configuration object
* Screen resize (or reorientation) event listeners for dynamic changes to the screen size
* Switches internal usage of string based current screen type to screenTypeObject for quicker lookups and ...
* More accurate body-class application with no overlap from previous executions.

PLAT-23335: Added proportional scaling support to Resolution Independence

---

src/DataList/DataList.js

When mixin have exists true option, it is not copy falsy value.
We added spotlightRememberFocus option for container that is try to find
nearest neighbor on 5way focus enters into container. The undefined and
true value have same meaning by definition here.
Problem happens when initcontainer of DataList is copying
scrollerOptions which is having spotlightRememberFocus false.
Because, mixin is not copy falsy value and undefined means true
for spotlightRememberFocus property.
We remove exists option from initContainer mixin. So, it can copy
falsy value.

ENYO-3403: Remove exists option from initContainer mixin.

---

src/LightPanels/LightPanels.js

To fit desired timing, it's better to delay removing 'shifted' class.
Enyo-DCO-1.1-Signed-off-by: Yeram Choi (yeram.choi@lge.com)

ENYO-3395: remove 'shifted' class asynchronously

---

src/Popup/Popup.js

Issue
Scrim is not hidden when notification is destroyed in showing status.
Fix
When notification is destroyed, showHideScrim is called to hide scrim.
Enyo-DCO-1.1-Signed-off-by: Yeram Choi (yeram.choi@lge.com)

ENYO-3431 Scrim isn't hidden when notification is destroyed in showing

---

src/NewDataList.js

It seems like re-calculate scroll boundaries before refreshThreshold()
since we're using scrollBounds as a base number in refreshThreshold().
Enyo-DCO-1.1-Signed-off-by: Yeram Choi (yeram.choi@lge.com)

ENYO-3376: Calculate scroll boundaries right before refreshThreshold

---

src/ShowingTransitionSupport.js

key for the first time.
Issue:
ShowingTransitionSupport is calling showingChanged from create. The
showingChanged is set initial css state and call timing methods like
hiding, hidden, showing, shown. Problem happens when create Notification
dynamically because hidingMethod is called on create and try to re-spot
on activator but activator is null (cached on showingMethod). And if
user destroy popup without hide, then hidingMethod is not even called.
Fix:
Check hasNode before calling timing methods. And call showingChanged
from destroy before calling clearJobFn to ensure timing functions called
before destroy.

ENYO-3444: Notification popup returns focus to first item if press back

---

src/NewDataList.js
src/NewThumb/NewThumb.js
src/resolution.js

reinitialize enyo/resolution before components receive resize event

Fixes PLAT-24979

---

src/VerticalDelegate.js

Issue:
We do call updateBounds and cache when _updateBounds is true, and use
cached value when _updateBounds is false or undefined. The _updateBounds
is undefined on create and set to false from updateBounds. We call
updateBounds form rendered and didResize. So, there is a change of
calling height() when _updateBounds is undefined.
Fix:
We can avoid this change by setting _updateBounds to true on initList
which means it need to cache. Then height() will call updateBounds to
measure metric and DOM.getBounds will return invalid values but there
will be no null reference error.

ENYO-3465: height() of verticalDelegate report null reference error

---

src/resolution.js

And measures `document.body` instead of `window` so components are scaled based on Enyo's available rendering area rather than the physical window dimensions.
Height is also factored into the check now too.

PLAT-47295: Resolution now better matches the screen shape
